### ISSUE TITLE
How to build a release with custom plugin ?

### ISSUE THREAD

**Issue by EastWoodYang** [apache/incubator-answer#657]
How to build a release with custom plugin ?

**Comment by EastWoodYang** [comment]
use 
**answer build --with ...**
build failed.

```
The dependency was already listed in devDependencies.
If you want to make it a prod dependency, then move it manually.

. prepare$ pnpm build:packages
. prepare: > answer-static@0.1.0 build:packages /home/runner/work/answer/answer/answer_build592811159/vendor/github.com/answerdev/answer/ui
. prepare: > pnpm -r --filter=./src/plugins/* run build
. prepare: No projects matched the filters in "/home/runner/work/answer/answer/answer_build592811159/vendor/github.com/answerdev/answer/ui"
. prepare: Done
Done in 15.6s
[pnpm build]

> answer-static@0.1.0 build /home/runner/work/answer/answer/answer_build592811159/vendor/github.com/answerdev/answer/ui
> react-app-rewired build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Failed to compile.

[eslint] 
src/plugins/index.ts
  Line 2:1:  Delete `⏎`  prettier/prettier

Search for the keywords to learn more about each error.


 ELIFECYCLE  Command failed with exit code 1.
build failed exit status 1
```

**Comment by shuashuai** [comment]
Please provide the node and pnpm versions you are using.

**Comment by EastWoodYang** [comment]
用的Github Action，报上面的错误

```
name: Build

on:
  workflow_dispatch:

jobs:
  build-goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build
        # run: ./answer build --with conector-wechat@1.0.0=${{ github.workspace }}/connector-wechat
        run: ./answer build --with github.com/apache/incubator-answer-plugins/connector-github
```
