### ISSUE TITLE
upgrade 1.3.1-RC2 to 1.3.1, question page is 500

### ISSUE THREAD

**Issue by Dev-Wiki** [apache/incubator-answer#995]
## Describe the bug

docker compose install,  Modify image Version to upgrade, the question page is 500, tag and index page is no problem.

https://qa.devwiki.net/questions/D1r3/hong-meng-app-ru-he-huo-qu-shou-ji-xin-xi

![image](https://github.com/apache/incubator-answer/assets/12946956/cccdfcf2-a1d6-4d5c-a71a-19b4857f46a4)

### Platform

```
version: '3'

services:
  answer:
    image: apache/answer:1.3.1
    restart: always
    ports:
      - '9083:80'
    volumes:
      - /share/Docker/answer/data:/data
```

back to 1.3.1-RC2 not recovery
